run = True
ZIP_DIR = 'D:\\Zip'
Image = ('.png', '.jpg', '.jpeg', '.gif', '.tiff', '.psd', '.raw', '.bmp', '.heif', '.indd', '.svg', '.ai', '.eps', '.ico', '.webp')
PYTHON_DIR = 'D:\\Python'
Video = ('.mp4', '.mov', '.wmv', '.avi', '.avchd', '.flv', '.f4v', '.swf', '.mkv', '.webm', '.mng', '.gifv', '.mpg', '.mp2', '.mpeg', '.mpe', '.mpv', '.ogg', '.m4p', '.m4v', '.wmv', '.mov', '.qt', '.flv', '.swf', '.avchd')
audio_formats = ('.mp3', '.wav', '.aiff', '.flac', '.aac', '.ogg', '.wma', '.m4a', '.ape', '.alac', '.dsd')
PDF = "PDF"
DOCX = "DOCX"
ZIP = "ZIP"
IMAGE = "Image"
Python = "Python"
VIDEO = "Video"
MUSIC = "Music"
Torrent = "Torrent"