name: Build

on:
  push:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cx_freeze
      - name: Build
        id: build
        run: |
          python setup.py build
      - name: Rename build folder
        run: |
          mv build_windows auto-download-sorter
      - name: Zip build folder
        run: |
          7z a auto-download-sorter.zip auto-download-sorter
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.2.0
          release_name: Release v1.2.0
          body: |
            updated the config handler
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./auto-download-sorter.zip
          asset_name: auto-download-sorter.zip
          asset_content_type: application/zip
